spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: JAVA_OPTIONS
            value: "-Dfabric8.k8s.secrets.api.enabled=true"
          - name: MYSQL_SERVICE_NAME
            value: mysql
          - name: MYSQL_SERVICE_DATABASE
            value: sampledb
          - name: MYSQL_SERVICE_USERNAME
            value: kalix
          - name: MYSQL_SERVICE_PASSWORD
            value: kalix
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health-check
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness-check
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1