spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: JAVA_OPTIONS
            value: "-Dfabric8.config.plugin.enabled=true -Dfabric8.k8s.secrets.api.enabled=true"
          - name: MYSQL_SERVICE_NAME
            value: mysql
          - name: MYSQL_SERVICE_DATABASE
            value: sampledb
          - name: MYSQL_SERVICE_USERNAME
            value: kalix
          - name: MYSQL_SERVICE_PASSWORD
            value: kalix